DROP DATABASE IF EXISTS M5_BBDDJuego;
CREATE DATABASE M5_BBDDJuego;
USE M5_BBDDJuego;

CREATE TABLE Jugador(
	ID INT,
	NOMBRE VARCHAR(20),
	CONTRASEÑA VARCHAR(20),
	PRIMARY KEY (ID),
	PRIMARY KEY (NOMBRE)
)ENGINE=InnoDB;

CREATE TABLE Partida(
	ID INT,
	FECHA VARCHAR(15),
	HORA VARCHAR(15),
	MINUTOS INT,
	GANADOR VARCHAR(20),
	PARTICIPANTES INT,
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE Relacion(
	IDJUGADOR INT,
	IDPARTIDA INT,
	FOREIGN KEY (IDJUGADOR) REFERENCES Jugador(ID),
	FOREIGN KEY (IDPARTIDA) REFERENCES Partida(ID)
)ENGINE=InnoDB;

INSERT INTO Jugador VALUES (1,'Taylor Swift','DondaIsShit1');
INSERT INTO Jugador VALUES (2,'Kayne West','ShakeItUpIsShit2');


INSERT INTO Partida VALUES (1,'10/03/2023','20:00',30,'Kayne West',2);
INSERT INTO Partida VALUES (2,'13/03/2023','10:00',20,'Kayne West',4);
INSERT INTO Partida VALUES (3,'17/03/2023','10:00',60,'Kayne West',5);
INSERT INTO Partida VALUES (4,'19/03/2023','20:00',10,'Kayne West',6);


INSERT INTO Relacion VALUES (1,1);
INSERT INTO Relacion VALUES (1,2);
INSERT INTO Relacion VALUES (1,3);
INSERT INTO Relacion VALUES (1,4);

